import React, { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    nav_home: "Home", nav_about: "About", nav_services: "Solutions", nav_calc: "ROI Calculator", nav_projects: "Portfolio", nav_contact: "Get Consultation",
    hero_badge: "Tier-1 Solar EPC Leader", hero_title: "Architecting Sustainable <span class='gradient-text'>Energy Independence</span>", hero_desc: "High-performance industrial, commercial, and residential turnkey solar PV systems optimized for maximum generation and ROI.", hero_btn1: "Calculate Savings", hero_btn2: "Corporate Proposal",
    track_curr: "Current Generation", track_co2: "CO2 Reduced Today",
    about_tag: "Corporate Profile", about_title: "Engineered For Decades of Reliable Power", about_desc: "Affiliated with ACE E&C with over 30 years of large-scale structural mastery. PT. ACE ENERGY SERVICE delivers premier asset maintenance and robust solar EPC installations across South East Asia, ensuring stringent ISO standards and optimized Levelized Cost of Energy (LCOE).",
    about_stat2: "B2 Grade & ISO Certified", about_stat4: "IDR 1.2T Group Scaling",
    counter1: "Years of Infrastructure Mastery", counter3: "Commissioned Solar Assets",
    calc_title: "Estimate Your Solar Yield Instantly", calc_subtitle: "Input your average monthly electrical expenditures to see how much you could optimize.", calc_label: "Monthly Electricity Bill (IDR):",
    calc_res1: "Est. Monthly Savings", calc_res2: "Recommended System Size", calc_res3: "CO2 Offset / Year",
    services_tag: "Ecosystem Matrix", services_title: "Comprehensive Energy Capabilities",
    service1_title: "Predictive Solar O&M", service1_desc: "Drone thermography diagnostics, 24/7 cloud SCADA analytics, and rapid response cleaning systems.",
    service2_title: "Industrial Turnkey EPC", service2_desc: "Tailored zero-capital options (PPA) or high-yield CAPEX engineering for mega factories.",
    service3_title: "Residential Luxury Microgrids", service3_desc: "Sleek smart-home integrated rooftops with 25-year structural warranties.",
    service6_title: "BESS Utility Storage", service6_desc: "Peak shifting backup batteries maintaining power reliability during unstable grid micro-cuts.",
    projects_tag: "Proven Implementations", projects_title: "High-Yield Assets",
    filter_all: "All Installations", filter_industrial: "Heavy Industrial", filter_commercial: "Commercial", filter_rooftop: "Rooftop Systems",
    contact_title: "Initiate Your Energy Transition", contact_tag: "Schedule an on-site engineering assessment with our senior technicians.",
    contact_name: "Your Name", contact_email: "Business Email", contact_message: "Describe your energy requirements...", contact_send: "Request Site Survey",
    copyright: "&copy; 2026 ACE ENERGY SERVICE. All asset rights architecture preserved.",
    modal_button: "Inquire For Similar Scale",
    footer_tagline: "“Indonesia Solar PV Energy Expert”",
    strength2_title: "International Tier-1 Audited",
    calc_step1Label: 'Initial Info',
    calc_step2Label: 'Technical Needs',
    calc_step3Label: 'Recommendations',
    calc_step1Title: 'Step 1: Initial Information',
    calc_step1Desc: 'Please enter your name, phone, and active email to compile an official solar energy proposal.',
    calc_clientNameLabel: 'Full Name / Company Name',
    calc_clientNamePlaceholder: 'Enter your full name...',
    calc_clientPhoneLabel: 'Phone Number / WhatsApp',
    calc_clientPhonePlaceholder: 'Example: 087770051282',
    calc_clientEmailLabel: 'Email Address',
    calc_clientEmailPlaceholder: 'Example: name@domain.com',
    calc_alertFillProfile: 'Please complete your Name, Phone Number, and Email profile first.',
    calc_step2Title: 'Step 2: Technical Data & Power Consumption',
    calc_step2Desc: 'Enter your clean roof area and utility power information to calculate the recommended solar capacity.',
    calc_roofAreaLabel: 'Available Roof Area (m²)',
    calc_roofAreaNote: 'Standard area: 1 kWp solar panel requires ± 5-6 m² of clean roof area.',
    calc_gridCapacityLabel: 'PLN Grid Connection Capacity (VA)',
    calc_monthlyBillLabel: 'Average Monthly Electricity Bill (IDR)',
    calc_idealKwp: 'Ideal Capacity',
    calc_maxKwp: 'Roof Limit',
    calc_recKwp: 'Recommended Capacity',
    calc_step3Title: 'Step 3: ROI Analysis & Product Ranking',
    calc_step3Desc: 'ROI analysis completed. Below is the solar feasibility financial report and top solar product recommendations based on your inputs.',
    calc_estSavings: 'Est. Monthly Savings',
    calc_paybackPeriod: 'Payback Period',
    calc_years: 'Years',
    calc_co2Offset: 'CO2 Offset / Year',
    calc_tons: 'Tons',
    calc_selectedPanels: 'Selected Solar Panels Recommendations for You',
    calc_price: 'Price',
    calc_efficiency: 'Efficiency',
    calc_warranty: 'Warranty',
    calc_noProducts: 'No products passed the roof compatibility filter rules.',
    calc_downloadPdf: 'Download Official PDF Report',
    calc_consultationText: 'Want a free physical site survey and a customized official quotation from the ACE Engineering Team?',
    calc_consultationLink: 'Click Here for Further Consultation',
    calc_btnBack: 'Back',
    calc_btnNext: 'Next',
    calc_pdfTitle: 'SOLAR FEASIBILITY ANALYSIS REPORT',
    calc_pdfDocNo: 'Document No.',
    calc_pdfDate: 'Date',
    calc_pdfSub: 'Technical Report on Solar Energy Investment Recommendation',
    calc_pdfSec1: '1. General Client Information',
    calc_pdfClientName: 'Client Name / Company',
    calc_pdfClientPhone: 'Phone Number / WhatsApp',
    calc_pdfClientEmail: 'Email Address',
    calc_pdfSec2: '2. Technical Input Parameters',
    calc_pdfParam: 'Input Parameter',
    calc_pdfVal: 'Input Value',
    calc_pdfDesc: 'Description',
    calc_pdfRoofAreaDesc: 'Physical area allocated for PV panel installation.',
    calc_pdfGridDesc: 'Active electricity grid capacity at the site.',
    calc_pdfBillDesc: 'Basis for daily energy needs calculation.',
    calc_pdfSec3: '3. Capacity Analysis & ROI Evaluation Results',
    calc_pdfMetric: 'System Evaluation Metric',
    calc_pdfEstVal: 'Estimated Value',
    calc_pdfTechDesc: 'Technical Description',
    calc_pdfRecKwpDesc: 'Optimal capacity adjusted to roof area & PLN grid capacity.',
    calc_pdfAnnGen: 'Estimated Electricity Generation',
    calc_pdfAnnGenDesc: 'Referring to average daily sun hours in Indonesia.',
    calc_pdfAnnGenUnit: 'kWh / Year',
    calc_pdfAnnSavings: 'Estimated Financial Savings',
    calc_pdfAnnSavingsDesc: 'Or equivalent to {savings} / Month.',
    calc_pdfPaybackDesc: 'Assuming average standard ACE system cost.',
    calc_pdfCo2Desc: 'Green certification contributing to sustainability reporting.',
    calc_pdfSec4: '4. Ranking of Best Solar Panel Product Recommendations',
    calc_pdfSec4Note: 'Automatically sorted based on performance priority, manufacturer warranty duration, and economic investment value.',
    calc_pdfRank: 'Rank',
    calc_pdfPanelBrand: 'Panel Brand & Model',
    calc_pdfTechSpec: 'Technical Specification',
    calc_pdfEstPrice: 'Estimated Price',
    calc_pdfCloseness: 'Compatibility Level',
    calc_pdfFormNote: 'Note: To proceed with further consultation and scheduling a detailed physical survey, please contact the engineering team via the following Google Form questionnaire link: {url}',
    calc_pdfCreatedBy: 'Prepared By,',
    calc_pdfApprovedBy: 'Approved By,',
    calc_pdfClientRep: 'Client Representative / Partner',
    calc_pdfSigLine: 'Signature & Full Name',
    calc_pdfSeniorTech: 'Senior Technician Engineer'
  },
  id: {
    nav_home: "Beranda", nav_about: "Tentang Kami", nav_services: "Solusi", nav_calc: "Kalkulator ROI", nav_projects: "Portofolio", nav_contact: "Konsultasi Gratis",
    hero_badge: "Pemimpin EPC Surya Tier-1", hero_title: "Membangun Kemandirian <span class='gradient-text'>Energi Berkelanjutan</span>", hero_desc: "Sistem PLTS atap industrial, komersial, dan residensial berkinerja tinggi yang dioptimalkan untuk hasil generasi dan ROI maksimal.", hero_btn1: "Hitung Penghematan", hero_btn2: "Proposal Perusahaan",
    track_curr: "Generasi Saat Ini", track_co2: "Reduksi CO2 Hari Ini",
    about_tag: "Profil Perusahaan", about_title: "Dirancang Untuk Keandalan Energi Puluhan Tahun", about_desc: "Terafiliasi dengan ACE E&C yang memiliki lebih dari 30 tahun keahlian struktural skala besar. PT. ACE ENERGY SERVICE menghadirkan pemeliharaan aset premium dan instalasi EPC surya yang kokoh di seluruh Asia Tenggara, memastikan standar ISO yang ketat dan Levelized Cost of Energy (LCOE) yang optimal.",
    about_stat2: "Sertifikasi Kelas B2 & ISO", about_stat4: "Skala Grup IDR 1.2T",
    counter1: "Tahun Pengalaman Infrastruktur", counter3: "Aset Surya yang Dioperasikan",
    calc_title: "Estimasi Hasil Panel Surya Anda Seketika", calc_subtitle: "Masukkan pengeluaran listrik bulanan Anda untuk melihat potensi optimalisasi penghematan.", calc_label: "Tagihan Listrik Bulanan (IDR):",
    calc_res1: "Estimasi Hemat Bulanan", calc_res2: "Rekomendasi Ukuran Sistem", calc_res3: "Reduksi CO2 / Tahun",
    services_tag: "Matriks Ekosistem", services_title: "Kemampuan Energi Komprehensif",
    service1_title: "O&M Surya Prediktif", service1_desc: "Diagnostik termografi drone, analitik cloud SCADA 24/7, dan sistem pembersihan respons cepat.",
    service2_title: "EPC Turnkey Industrial", service2_desc: "Pilihan tanpa modal (PPA) atau teknik CAPEX hasil tinggi yang disesuaikan untuk pabrik mega.",
    service3_title: "Luxury Microgrid Residensial", service3_desc: "Atap terintegrasi rumah pintar yang elegan dengan garansi struktural hingga 25 tahun.",
    service6_title: "Penyimpanan Utilitas BESS", service6_desc: "Baterai cadangan penggeser beban puncak menjaga keandalan daya saat terjadi pemadaman mikro grid.",
    projects_tag: "Implementasi Terbukti", projects_title: "Aset Hasil Tinggi",
    filter_all: "Semua Instalasi", filter_industrial: "Industri Berat", filter_commercial: "Komersial", filter_rooftop: "Sistem Rooftop",
    contact_title: "Mulai Transisi Energi Anda", contact_tag: "Jadwalkan penilaian teknik langsung di lokasi bersama teknisi senior kami.",
    contact_name: "Nama Anda", contact_email: "Email Bisnis", contact_message: "Jelaskan kebutuhan energi Anda...", contact_send: "Ajukan Survei Lokasi",
    copyright: "&copy; 2026 ACE ENERGY SERVICE. Seluruh arsitektur hak aset dilindungi.",
    modal_button: "Ajukan Skala Serupa",
    footer_tagline: "“Indonesia Solar PV Energy Expert”",
    strength2_title: "Audit Tier-1 Internasional",
    calc_step1Label: 'Informasi Awal',
    calc_step2Label: 'Kebutuhan PLTS',
    calc_step3Label: 'Hasil Rekomendasi',
    calc_step1Title: 'Langkah 1: Informasi Awal',
    calc_step1Desc: 'Harap masukkan nama, nomor telepon, dan email aktif Anda untuk menyusun proposal penawaran PLTS resmi.',
    calc_clientNameLabel: 'Nama Lengkap / Nama Perusahaan',
    calc_clientNamePlaceholder: 'Masukkan nama lengkap Anda...',
    calc_clientPhoneLabel: 'Nomor Telepon / WhatsApp',
    calc_clientPhonePlaceholder: 'Contoh: 087770051282',
    calc_clientEmailLabel: 'Alamat Email',
    calc_clientEmailPlaceholder: 'Contoh: nama@domain.com',
    calc_alertFillProfile: 'Mohon lengkapi profil Nama, Nomor Telepon, dan Email terlebih dahulu.',
    calc_step2Title: 'Langkah 2: Data Teknis & Konsumsi Listrik',
    calc_step2Desc: 'Masukkan luas atap bersih dan informasi kelistrikan PLN Anda untuk menghitung kapasitas PLTS yang disarankan.',
    calc_roofAreaLabel: 'Luas Atap yang Tersedia (m²)',
    calc_roofAreaNote: 'Standard luas: 1 kWp panel surya membutuhkan ± 5-6 m² area atap bersih.',
    calc_gridCapacityLabel: 'Sambungan Kontrak Daya Listrik PLN (VA)',
    calc_monthlyBillLabel: 'Tagihan Listrik Rata-Rata Bulanan (IDR)',
    calc_idealKwp: 'Kebutuhan Ideal',
    calc_maxKwp: 'Batas Maks Atap',
    calc_recKwp: 'Rekomendasi Kapasitas',
    calc_step3Title: 'Langkah 3: Hasil Analisis ROI & Pemeringkatan Produk',
    calc_step3Desc: 'Analisis ROI telah selesai. Berikut adalah laporan finansial kelayakan PLTS dan rekomendasi produk surya terbaik berdasarkan masukan Anda.',
    calc_estSavings: 'Estimasi Hemat Bulanan',
    calc_paybackPeriod: 'Masa Balik Modal',
    calc_years: 'Tahun',
    calc_co2Offset: 'Reduksi CO2 / Tahun',
    calc_tons: 'Ton',
    calc_selectedPanels: 'Rekomendasi Panel Surya Terpilih untuk Anda',
    calc_price: 'Harga',
    calc_efficiency: 'Efisiensi',
    calc_warranty: 'Garansi',
    calc_noProducts: 'Tidak ada produk yang lolos filtering aturan kecocokan atap.',
    calc_downloadPdf: 'Unduh Laporan PDF Resmi',
    calc_consultationText: 'Ingin survei lokasi fisik secara gratis dan penawaran harga resmi yang disesuaikan dari Tim Engineering ACE?',
    calc_consultationLink: 'Klik Selengkapnya Untuk Konsultasi Lebih Lanjut',
    calc_btnBack: 'Kembali',
    calc_btnNext: 'Lanjutkan',
    calc_pdfTitle: 'LAPORAN ANALISIS KELAYAKAN PLTS',
    calc_pdfDocNo: 'No Dokumen',
    calc_pdfDate: 'Tanggal',
    calc_pdfSub: 'Laporan Teknis Rekomendasi Investasi Energi Surya',
    calc_pdfSec1: '1. Informasi Umum Klien',
    calc_pdfClientName: 'Nama Klien / Perusahaan',
    calc_pdfClientPhone: 'Nomor Telepon / WhatsApp',
    calc_pdfClientEmail: 'Alamat Email',
    calc_pdfSec2: '2. Parameter Masukan Teknis',
    calc_pdfParam: 'Parameter Masukan',
    calc_pdfVal: 'Nilai Input',
    calc_pdfDesc: 'Keterangan',
    calc_pdfRoofAreaDesc: 'Luas fisik yang dialokasikan untuk instalasi panel PV.',
    calc_pdfGridDesc: 'Kapasitas jaringan daya listrik aktif di lokasi.',
    calc_pdfBillDesc: 'Dasar perhitungan kebutuhan energi harian.',
    calc_pdfSec3: '3. Hasil Analisis Kapasitas & Evaluasi ROI',
    calc_pdfMetric: 'Metrik Evaluasi Sistem',
    calc_pdfEstVal: 'Nilai Estimasi',
    calc_pdfTechDesc: 'Keterangan Teknis',
    calc_pdfRecKwpDesc: 'Kapasitas optimal yang disesuaikan luas atap & daya PLN.',
    calc_pdfAnnGen: 'Estimasi Produksi Energi Listrik',
    calc_pdfAnnGenDesc: 'Mengacu pada sun hours harian rata-rata di Indonesia.',
    calc_pdfAnnGenUnit: 'kWh / Tahun',
    calc_pdfAnnSavings: 'Estimasi Penghematan Finansial',
    calc_pdfAnnSavingsDesc: 'Atau setara dengan {savings} / Bulan.',
    calc_pdfPaybackDesc: 'Asumsi biaya sistem rata-rata standar ACE.',
    calc_pdfCo2Desc: 'Sertifikasi hijau kontribusi pelaporan keberlanjutan.',
    calc_pdfSec4: '4. Urutan Rekomendasi Produk Panel Surya Terbaik',
    calc_pdfSec4Note: 'Diurutkan secara otomatis berdasarkan prioritas performa, durasi garansi pabrikan, dan nilai ekonomis investasi.',
    calc_pdfRank: 'Peringkat',
    calc_pdfPanelBrand: 'Merek & Model Panel',
    calc_pdfTechSpec: 'Spesifikasi Teknis',
    calc_pdfEstPrice: 'Estimasi Harga',
    calc_pdfCloseness: 'Tingkat Kecocokan',
    calc_pdfFormNote: 'Catatan: Untuk melakukan konsultasi lanjutan dan penjadwalan survei fisik terperinci, silakan hubungi tim teknik melalui tautan kuesioner Google Form berikut: {url}',
    calc_pdfCreatedBy: 'Dibuat Oleh,',
    calc_pdfApprovedBy: 'Disetujui Oleh,',
    calc_pdfClientRep: 'Perwakilan Klien / Kemitraan',
    calc_pdfSigLine: 'Tanda Tangan & Nama Terang',
    calc_pdfSeniorTech: 'Technician Engineer Senior'
  },
  ko: {
    nav_home: "홈", nav_about: "회사소개", nav_services: "솔루션", nav_calc: "ROI 계산기", nav_projects: "포트폴리오", nav_contact: "무료 상담",
    hero_badge: "Tier-1 태양광 EPC 리더", hero_title: "지속 가능한 <span class='gradient-text'>에너지 자립</span> 설계", hero_desc: "최대 발전량 및 투자 수익률(ROI)에 최적화된 고성능 산업용, 상업용, 주거용 턴키 태양광 발전 시스템.", hero_btn1: "절감액 계산하기", hero_btn2: "기업 제안서 요청",
    track_curr: "현재 발전량", track_co2: "오늘 탄소 절감량",
    about_tag: "기업 프로필", about_title: "수십 년간 신뢰할 수 있는 전력 엔지니어링", about_desc: "30년 이상의 대규모 구조물 공사 노하우를 보유한 ACE E&C와 제휴하여, PT. ACE ENERGY SERVICE는 동남아시아 전역에 최고 수준의 자산 관리 및 탄탄한 태양광 EPC 설치를 제공하며 엄격한 ISO 표준과 최적화된 균등화발전비용(LCOE)을 보장합니다.",
    about_stat2: "B2 등급 및 ISO 인증획득", about_stat4: "그룹 자산 규모 1.2조 IDR",
    counter1: "기반 시설 마스터 경력(년)", counter3: "운영 중인 태양광 자산",
    calc_title: "태양광 발전량 즉시 추정", calc_subtitle: "월평균 전기 요금을 입력하여 얼마나 최적화할 수 있는지 즉시 확인하십시오.", calc_label: "월간 전기 요금 (IDR):",
    calc_res1: "예상 월간 절감액", calc_res2: "권장 시스템 용량", calc_res3: "연간 탄소 상쇄량",
    services_tag: "에코시스템 매트릭스", services_title: "종합 에너지 역량",
    service1_title: "예측형 태양광 O&M", service1_desc: "드론 열화상 진단, 24/7 클라우드 SCADA 분석 및 신속 대응 세척 시스템.",
    service2_title: "산업용 턴키 EPC", service2_desc: "대형 공장을 위한 맞춤형 제로 자본 옵션 (PPA) 또는 고수익 CAPEX 엔지니어링.",
    service3_title: "주거용 럭셔리 마이크로그리드", service3_desc: "25년 구조 보증이 포함된 세련된 스마트홈 통합형 루프탑.",
    service6_title: "BESS 유틸리티 저장장치", service6_desc: "불안정한 그리드 미세 단전 시 전력 신뢰성을 유지하는 피크 시프팅 백업 배터리.",
    projects_tag: "검증된 구현 사례", projects_title: "고수익 자산",
    filter_all: "전체 설치 사례", filter_industrial: "중공업 부문", filter_commercial: "상업 부문", filter_rooftop: "루프탑 시스템",
    contact_title: "에너지 전환 시작하기", contact_tag: "수석 엔지니어와 함께 현장 엔지니어링 평가 일정을 잡으십시오.",
    contact_name: "이름", contact_email: "회사 이메일", contact_message: "필요한 에너지 요구 사항을 설명하십시오...", contact_send: "현장 실사 요청",
    copyright: "&copy; 2026 ACE ENERGY SERVICE. 모든 자산 권리 아키텍처가 보존됩니다.",
    modal_button: "유사 규모 문의하기",
    footer_tagline: "“Indonesia Solar PV Energy Expert”",
    strength2_title: "국제 Tier-1 감사 획득",
    calc_step1Label: '기본 정보',
    calc_step2Label: '태양광 요구사양',
    calc_step3Label: '추천 결과',
    calc_step1Title: '1단계: 기본 정보',
    calc_step1Desc: '공식 태양광 제안서 작성을 위해 이름, 전화번호 및 이메일을 입력해 주세요.',
    calc_clientNameLabel: '성명 / 회사명',
    calc_clientNamePlaceholder: '성명을 입력해 주세요...',
    calc_clientPhoneLabel: '전화번호 / WhatsApp',
    calc_clientPhonePlaceholder: '예: 087770051282',
    calc_clientEmailLabel: '이메일 주소',
    calc_clientEmailPlaceholder: '예: name@domain.com',
    calc_alertFillProfile: '먼저 이름, 전화번호, 이메일 정보를 입력해 주세요.',
    calc_step2Title: '2단계: 기술 데이터 및 전력 소비량',
    calc_step2Desc: '권장 태양광 용량을 계산하기 위해 가용 지붕 면적과 한전(PLN) 계약 전력 정보를 입력해 주세요.',
    calc_roofAreaLabel: '가용 지붕 면적 (m²)',
    calc_roofAreaNote: '표준 면적: 태양광 패널 1 kWp 설치 시 약 5-6 m²의 빈 지붕 공간이 필요합니다.',
    calc_gridCapacityLabel: 'PLN 계약 전력 용량 (VA)',
    calc_monthlyBillLabel: '월평균 전기 요금 (IDR)',
    calc_idealKwp: '이상적 용량',
    calc_maxKwp: '지붕 한계',
    calc_recKwp: '권장 용량',
    calc_step3Title: '3단계: ROI 분석 및 제품 순위',
    calc_step3Desc: 'ROI 분석이 완료되었습니다. 입력하신 정보를 바탕으로 한 태양광 타당성 재무 보고서 및 최적의 제품 추천 결과입니다.',
    calc_estSavings: '월간 예상 절감액',
    calc_paybackPeriod: '투자 회수 기간',
    calc_years: '년',
    calc_co2Offset: '연간 CO2 감축량',
    calc_tons: '톤',
    calc_selectedPanels: '고객님을 위한 추천 태양광 패널',
    calc_price: '가격',
    calc_efficiency: '효율',
    calc_warranty: '보증',
    calc_noProducts: '지붕 호환성 필터 규칙을 통과한 제품이 없습니다.',
    calc_downloadPdf: '공식 PDF 보고서 다운로드',
    calc_consultationText: 'ACE 엔지니어링 팀의 무료 현장 실사 및 맞춤형 공식 견적을 원하십니까?',
    calc_consultationLink: '추가 상담을 위해 여기를 클릭하세요',
    calc_btnBack: '이전',
    calc_btnNext: '다음',
    calc_pdfTitle: '태양광 발전 타당성 분석 보고서',
    calc_pdfDocNo: '문서 번호',
    calc_pdfDate: '일자',
    calc_pdfSub: '태양광 에너지 투자 추천 기술 보고서',
    calc_pdfSec1: '1. 고객 일반 정보',
    calc_pdfClientName: '고객명 / 회사명',
    calc_pdfClientPhone: '전화번호 / WhatsApp',
    calc_pdfClientEmail: '이메일 주소',
    calc_pdfSec2: '2. 기술 입력 매개변수',
    calc_pdfParam: '입력 항목',
    calc_pdfVal: '입력값',
    calc_pdfDesc: '설명',
    calc_pdfRoofAreaDesc: '태양광 패널 설치를 위해 할당된 물리적 면적입니다.',
    calc_pdfGridDesc: '해당 사이트의 활성 전력 그리드 용량입니다.',
    calc_pdfBillDesc: '일일 에너지 요구량 계산의 기준입니다.',
    calc_pdfSec3: '3. 용량 분석 및 ROI 평가 결과',
    calc_pdfMetric: '시스템 평가 지표',
    calc_pdfEstVal: '추정값',
    calc_pdfTechDesc: '기술적 설명',
    calc_pdfRecKwpDesc: '지붕 면적 및 PLN 계약 전력에 맞게 조정된 최적의 용량입니다.',
    calc_pdfAnnGen: '예상 발전량',
    calc_pdfAnnGenDesc: '인도네시아의 일평균 일조 시간을 기준으로 합니다.',
    calc_pdfAnnGenUnit: 'kWh / 년',
    calc_pdfAnnSavings: '예상 재무 절감액',
    calc_pdfAnnSavingsDesc: '또는 월 {savings} 상당.',
    calc_pdfPaybackDesc: 'ACE 표준 평균 시스템 비용을 가정한 것입니다.',
    calc_pdfCo2Desc: '지속가능성 보고에 기여하는 친환경 인증입니다.',
    calc_pdfSec4: '4. 최적의 태양광 패널 제품 추천 순위',
    calc_pdfSec4Note: '성능 우수성, 제조업체 보증 기간 및 투자 경제성을 기준으로 자동 정렬되었습니다.',
    calc_pdfRank: '순위',
    calc_pdfPanelBrand: '패널 브랜드 및 모델',
    calc_pdfTechSpec: '기술 사양',
    calc_pdfEstPrice: '예상 가격',
    calc_pdfCloseness: '적합도',
    calc_pdfFormNote: '참고: 추가 상담 및 상세 현장 실사 일정을 잡으려면 다음 Google 설문지 링크를 통해 엔지니어링 팀에 문의하십시오: {url}',
    calc_pdfCreatedBy: '작성자:',
    calc_pdfApprovedBy: '승인자:',
    calc_pdfClientRep: '고객 대표 / 파트너',
    calc_pdfSigLine: '서명 및 성명',
    calc_pdfSeniorTech: '수석 기술 엔지니어'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('lang') || 'en';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('lang', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
