import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  en: {
    // Navigation
    nav_home: "Home", nav_about: "About", nav_strength: "Strengths", nav_services: "Services", nav_projects: "Projects", nav_contact: "Contact", nav_calculator: "Calculator",
    // Hero
    hero_badge: "Indonesia's No.1 Solar EPC & O&M", hero_title: "Empowering the Future with <span class='gold-text'>Clean Energy</span>", hero_desc: "Premium solar solutions — EPC, O&M, and renewable innovation for industries, commercial, residential, and agriculture.", hero_btn1: "Learn More", hero_btn2: "Contact Us",
    // About
    about_tag: "About Us", about_title: "Your Trusted Partner in Solar Energy", about_desc: "PT. ACE ENERGY SERVICE (affiliated with ACE E&C, a B2 Grade construction leader with 30+ years of expertise) delivers world-class solar PV solutions across Indonesia. Since 2019, we have specialized in EPC, O&M, and innovative renewable services — empowering businesses and homes with clean, reliable energy.", about_stat1: "300+ Group Projects", about_stat2: "ISO & B2 Licensed", about_stat3: "Nationwide Portfolio", about_stat4: "IDR 1.2T Sales (2023)",
    counter1: "Years of Excellence", counter2: "Major Projects", counter3: "Installed Capacity", counter4: "Corporate Clients",
    // Strengths
    strengths_tag: "Why Choose Us", strengths_title: "Our Core Strengths", strengths_sub: "Quality, reliability, and innovation in every project.",
    strength1_title: "Professional Team", strength1_desc: "Multidisciplinary experts engineering, legal & business synergy.",
    strength2_title: "International Standards", strength2_desc: "Designs & materials meet global IEC/ISO benchmarks.",
    strength3_title: "Sustainable Excellence", strength3_desc: "Optimized energy, long-term decarbonization impact.",
    strength4_title: "Tier-1 Materials", strength4_desc: "High-quality components & latest solar technology.",
    // Services
    services_tag: "Comprehensive Solutions", services_title: "Our Core Services", services_sub: "End-to-end solar energy services — from EPC to O&M and beyond",
    service1_title: "Solar PV O&M Service", service1_desc: "24/7 monitoring, predictive maintenance, rapid repair, and performance reporting.",
    service2_title: "Commercial Solar EPC", service2_desc: "For factories, malls, offices — turnkey installation & flexible financing.",
    service3_title: "Residential EPC", service3_desc: "Rooftop solar, 25-year panel warranty, monitoring app & post-install service.",
    service4_title: "Agricultural Solar", service4_desc: "Irrigation pumps, solar cooling, off-grid & hybrid — reduce costs.",
    service5_title: "REC Management", service5_desc: "I-REC certification, carbon neutrality reporting & ESG support.",
    service6_title: "BESS Solutions", service6_desc: "Energy storage: peak shifting, grid stability, backup power.",
    service7_title: "PPP & IPP Projects", service7_desc: "Build-Operate-Transfer (BOT), BOO models — experts in PPA structuring.",
    // Projects
    projects_tag: "Portfolio", projects_title: "Featured Projects", projects_sub: "Proven excellence across Indonesia's solar landscape",
    filter_all: "All Projects", filter_industrial: "Industrial", filter_commercial: "Commercial", filter_rooftop: "Rooftop",
    view_details: "View Details",
    // Legacy
    legacy_tag: "Our Legacy", legacy_title: "Why Choose ACE Energy Service?",
    legacy1: "<strong>B2 Grade License</strong> – Highest classification in Indonesia",
    legacy2: "<strong>Strict HSE & Quality Standards</strong> – ISO 9001, 14001, 45001",
    legacy3: "<strong>Non-CAPEX / Flexible Schemes</strong> – Reduce electricity costs without upfront investment",
    legacy4: "<strong>DUNS Registered & International REC Partners</strong>",
    milestone_title: "Milestones",
    milestone1: "<strong>2019</strong> – ACE ENERGY SERVICE launched",
    milestone2: "<strong>2021-2023</strong> – 11 MWp Hankook Tire, 4 MWp Hwa Seung",
    milestone3: "<strong>2025</strong> – Supporting 42.6 GW national solar target",
    // Contact
    contact_tag: "Get In Touch", contact_title: "Let's Build a Greener Future", contact_form_title: "Send a Message",
    contact_name: "Full Name", contact_email: "Email Address", contact_message: "Your message", contact_send: "Send Inquiry",
    // Footer
    footer_text: "Indonesia's No.1 Solar EPC & O&M since 2019.", footer_links: "Quick Links", footer_cert: "Certifications", footer_follow: "Follow Us", copyright: "© 2026 ACE ENERGY SERVICE. All rights reserved.",
    // Modal
    modal_capacity: "Capacity:", modal_button: "Contact Us",
    calc_step1Label: 'Initial Info',
    calc_step2Label: 'Technical Needs',
    calc_step3Label: 'Recommendations',
    calc_step1Title: 'Step 1: Initial Information',
    calc_step1Desc: 'Please enter your name, phone, and active email to compile an official solar energy proposal.',
    calc_clientNameLabel: 'Full Name / Company Name',
    calc_clientNamePlaceholder: 'Enter your full name...',
    calc_clientPhoneLabel: 'Phone Number / WhatsApp',
    calc_clientPhonePlaceholder: 'Example: 087770051282',
    calc_clientEmailLabel: 'Email Address',
    calc_clientEmailPlaceholder: 'Example: name@domain.com',
    calc_alertFillProfile: 'Please complete your Name, Phone Number, and Email profile first.',
    calc_step2Title: 'Step 2: Technical Data & Power Consumption',
    calc_step2Desc: 'Enter your clean roof area and utility power information to calculate the recommended solar capacity.',
    calc_roofAreaLabel: 'Available Roof Area (m²)',
    calc_roofAreaNote: 'Standard area: 1 kWp solar panel requires ± 5-6 m² of clean roof area.',
    calc_gridCapacityLabel: 'PLN Grid Connection Capacity (VA)',
    calc_monthlyBillLabel: 'Average Monthly Electricity Bill (IDR)',
    calc_idealKwp: 'Ideal Capacity',
    calc_maxKwp: 'Roof Limit',
    calc_recKwp: 'Recommended Capacity',
    calc_step3Title: 'Step 3: ROI Analysis & Product Ranking',
    calc_step3Desc: 'ROI analysis completed. Below is the solar feasibility financial report and top solar product recommendations based on your inputs.',
    calc_estSavings: 'Est. Monthly Savings',
    calc_paybackPeriod: 'Payback Period',
    calc_years: 'Years',
    calc_co2Offset: 'CO2 Offset / Year',
    calc_tons: 'Tons',
    calc_selectedPanels: 'Selected Solar Panels Recommendations for You',
    calc_price: 'Price',
    calc_efficiency: 'Efficiency',
    calc_warranty: 'Warranty',
    calc_noProducts: 'No products passed the roof compatibility filter rules.',
    calc_downloadPdf: 'Download Official PDF Report',
    calc_consultationText: 'Want a free physical site survey and a customized official quotation from the ACE Engineering Team?',
    calc_consultationLink: 'Click Here for Further Consultation',
    calc_btnBack: 'Back',
    calc_btnNext: 'Next',
    calc_pdfTitle: 'SOLAR FEASIBILITY ANALYSIS REPORT',
    calc_pdfDocNo: 'Document No.',
    calc_pdfDate: 'Date',
    calc_pdfSub: 'Technical Report on Solar Energy Investment Recommendation',
    calc_pdfSec1: '1. General Client Information',
    calc_pdfClientName: 'Client Name / Company',
    calc_pdfClientPhone: 'Phone Number / WhatsApp',
    calc_pdfClientEmail: 'Email Address',
    calc_pdfSec2: '2. Technical Input Parameters',
    calc_pdfParam: 'Input Parameter',
    calc_pdfVal: 'Input Value',
    calc_pdfDesc: 'Description',
    calc_pdfRoofAreaDesc: 'Physical area allocated for PV panel installation.',
    calc_pdfGridDesc: 'Active electricity grid capacity at the site.',
    calc_pdfBillDesc: 'Basis for daily energy needs calculation.',
    calc_pdfSec3: '3. Capacity Analysis & ROI Evaluation Results',
    calc_pdfMetric: 'System Evaluation Metric',
    calc_pdfEstVal: 'Estimated Value',
    calc_pdfTechDesc: 'Technical Description',
    calc_pdfRecKwpDesc: 'Optimal capacity adjusted to roof area & PLN grid capacity.',
    calc_pdfAnnGen: 'Estimated Electricity Generation',
    calc_pdfAnnGenDesc: 'Referring to average daily sun hours in Indonesia.',
    calc_pdfAnnGenUnit: 'kWh / Year',
    calc_pdfAnnSavings: 'Estimated Financial Savings',
    calc_pdfAnnSavingsDesc: 'Or equivalent to {savings} / Month.',
    calc_pdfPaybackDesc: 'Assuming average standard ACE system cost.',
    calc_pdfCo2Desc: 'Green certification contributing to sustainability reporting.',
    calc_pdfSec4: '4. Ranking of Best Solar Panel Product Recommendations',
    calc_pdfSec4Note: 'Automatically sorted based on performance priority, manufacturer warranty duration, and economic investment value.',
    calc_pdfRank: 'Rank',
    calc_pdfPanelBrand: 'Panel Brand & Model',
    calc_pdfTechSpec: 'Technical Specification',
    calc_pdfEstPrice: 'Estimated Price',
    calc_pdfCloseness: 'Compatibility Level',
    calc_pdfFormNote: 'Note: To proceed with further consultation and scheduling a detailed physical survey, please contact the engineering team via the following Google Form questionnaire link: {url}',
    calc_pdfCreatedBy: 'Prepared By,',
    calc_pdfApprovedBy: 'Approved By,',
    calc_pdfClientRep: 'Client Representative / Partner',
    calc_pdfSigLine: 'Signature & Full Name',
    calc_pdfSeniorTech: 'Senior Technician Engineer'
  },
  id: {
    nav_home: "Beranda", nav_about: "Tentang", nav_strength: "Keunggulan", nav_services: "Layanan", nav_projects: "Proyek", nav_contact: "Kontak", nav_calculator: "Kalkulator",
    hero_badge: "No.1 EPC & O&M Tenaga Surya di Indonesia", hero_title: "Memberdayakan Masa Depan dengan <span class='gold-text'>Energi Bersih</span>", hero_desc: "Solusi tenaga surya premium — EPC, O&M, dan inovasi terbarukan untuk industri, komersial, perumahan, dan pertanian.", hero_btn1: "Pelajari Lebih", hero_btn2: "Hubungi Kami",
    about_tag: "Tentang Kami", about_title: "Mitra Terpercaya Anda dalam Energi Surya", about_desc: "PT. ACE ENERGY SERVICE (afiliasi dengan ACE E&C, pemimpin konstruksi berlisensi B2 dengan pengalaman 30+ tahun) memberikan solusi PLTS kelas dunia di seluruh Indonesia. Sejak 2019, kami berspesialisasi dalam EPC, O&M, dan layanan terbarukan yang inovatif.", about_stat1: "300+ Proyek Grup", about_stat2: "Bersertifikat ISO & B2", about_stat3: "Portofolio Nasional", about_stat4: "Penjualan IDR 1,2T (2023)",
    counter1: "Tahun Keunggulan", counter2: "Proyek Utama", counter3: "Kapasitas Terpasang", counter4: "Klien Korporat",
    strengths_tag: "Mengapa Memilih Kami", strengths_title: "Kekuatan Utama Kami", strengths_sub: "Kualitas, keandalan, dan inovasi di setiap proyek.",
    strength1_title: "Tim Profesional", strength1_desc: "Ahli multidisiplin di bidang teknik, hukum, dan bisnis.",
    strength2_title: "Standar Internasional", strength2_desc: "Desain & material memenuhi tolok ukur IEC/ISO global.",
    strength3_title: "Keunggulan Berkelanjutan", strength3_desc: "Energi optimal, dampak dekarbonisasi jangka panjang.",
    strength4_title: "Material Tier-1", strength4_desc: "Komponen berkualitas tinggi & teknologi surya terkini.",
    services_tag: "Solusi Lengkap", services_title: "Layanan Inti Kami", services_sub: "Layanan energi surya ujung ke ujung — dari EPC hingga O&M dan seterusnya",
    service1_title: "Layanan O&M PLTS", service1_desc: "Pemantauan 24/7, pemeliharaan prediktif, perbaikan cepat, dan pelaporan kinerja.",
    service2_title: "EPC Komersial", service2_desc: "Untuk pabrik, mal, perkantoran — instalasi turnkey & pembiayaan fleksibel.",
    service3_title: "EPC Perumahan", service3_desc: "Atap surya, garansi panel 25 tahun, aplikasi monitoring & layanan purna jual.",
    service4_title: "Pertanian", service4_desc: "Pompa irigasi, pendingin surya, off-grid/hybrid — kurangi biaya.",
    service5_title: "Manajemen REC", service5_desc: "Sertifikasi I-REC, pelaporan netralitas karbon & dukungan ESG.",
    service6_title: "Solusi BESS", service6_desc: "Penyimpanan energi: pergeseran puncak, stabilitas jaringan, daya cadangan.",
    service7_title: "Proyek PPP & IPP", service7_desc: "Model BOT, BOO — ahli dalam penyusunan PPA & ladang surya skala besar.",
    projects_tag: "Portofolio", projects_title: "Proyek Unggulan", projects_sub: "Keunggulan terbukti di lanskap surya Indonesia",
    filter_all: "Semua Proyek", filter_industrial: "Industri", filter_commercial: "Komersial", filter_rooftop: "Atap",
    view_details: "Lihat Detail",
    legacy_tag: "Warisan Kami", legacy_title: "Mengapa Memilih ACE Energy Service?",
    legacy1: "<strong>Lisensi B2 Grade</strong> – Klasifikasi tertinggi di Indonesia",
    legacy2: "<strong>Standar HSE & Kualitas Ketat</strong> – ISO 9001, 14001, 45001",
    legacy3: "<strong>Skema Non-CAPEX / Fleksibel</strong> – Kurangi biaya listrik tanpa investasi awal",
    legacy4: "<strong>Terdaftar DUNS & Mitra REC Internasional</strong>",
    milestone_title: "Pencapaian",
    milestone1: "<strong>2019</strong> – ACE ENERGY SERVICE diluncurkan",
    milestone2: "<strong>2021-2023</strong> – 11 MWp Hankook Tire, 4 MWp Hwa Seung",
    milestone3: "<strong>2025</strong> – Mendukung target nasional 42,6 GW",
    // Contact
    contact_tag: "Hubungi Kami", contact_title: "Mari Bangun Masa Depan yang Lebih Hijau", contact_form_title: "Kirim Pesan",
    contact_name: "Nama Lengkap", contact_email: "Alamat Email", contact_message: "Pesan Anda", contact_send: "Kirim Pertanyaan",
    // Footer
    footer_text: "No.1 EPC & O&M Tenaga Surya di Indonesia sejak 2019.", footer_links: "Tautan Cepat", footer_cert: "Sertifikasi", footer_follow: "Ikuti Kami", copyright: "© 2026 ACE ENERGY SERVICE. Hak cipta dilindungi.",
    modal_capacity: "Kapasitas:", modal_button: "Hubungi Kami",
    calc_step1Label: 'Informasi Awal',
    calc_step2Label: 'Kebutuhan PLTS',
    calc_step3Label: 'Hasil Rekomendasi',
    calc_step1Title: 'Langkah 1: Informasi Awal',
    calc_step1Desc: 'Harap masukkan nama, nomor telepon, dan email aktif Anda untuk menyusun proposal penawaran PLTS resmi.',
    calc_clientNameLabel: 'Nama Lengkap / Nama Perusahaan',
    calc_clientNamePlaceholder: 'Masukkan nama lengkap Anda...',
    calc_clientPhoneLabel: 'Nomor Telepon / WhatsApp',
    calc_clientPhonePlaceholder: 'Contoh: 087770051282',
    calc_clientEmailLabel: 'Alamat Email',
    calc_clientEmailPlaceholder: 'Contoh: nama@domain.com',
    calc_alertFillProfile: 'Mohon lengkapi profil Nama, Nomor Telepon, dan Email terlebih dahulu.',
    calc_step2Title: 'Langkah 2: Data Teknis & Konsumsi Listrik',
    calc_step2Desc: 'Masukkan luas atap bersih dan informasi kelistrikan PLN Anda untuk menghitung kapasitas PLTS yang disarankan.',
    calc_roofAreaLabel: 'Luas Atap yang Tersedia (m²)',
    calc_roofAreaNote: 'Standard luas: 1 kWp panel surya membutuhkan ± 5-6 m² area atap bersih.',
    calc_gridCapacityLabel: 'Sambungan Kontrak Daya Listrik PLN (VA)',
    calc_monthlyBillLabel: 'Tagihan Listrik Rata-Rata Bulanan (IDR)',
    calc_idealKwp: 'Kebutuhan Ideal',
    calc_maxKwp: 'Batas Maks Atap',
    calc_recKwp: 'Rekomendasi Kapasitas',
    calc_step3Title: 'Langkah 3: Hasil Analisis ROI & Pemeringkatan Produk',
    calc_step3Desc: 'Analisis ROI telah selesai. Berikut adalah laporan finansial kelayakan PLTS dan rekomendasi produk surya terbaik berdasarkan masukan Anda.',
    calc_estSavings: 'Estimasi Hemat Bulanan',
    calc_paybackPeriod: 'Masa Balik Modal',
    calc_years: 'Tahun',
    calc_co2Offset: 'Reduksi CO2 / Tahun',
    calc_tons: 'Ton',
    calc_selectedPanels: 'Rekomendasi Panel Surya Terpilih untuk Anda',
    calc_price: 'Harga',
    calc_efficiency: 'Efisiensi',
    calc_warranty: 'Garansi',
    calc_noProducts: 'Tidak ada produk yang lolos filtering aturan kecocokan atap.',
    calc_downloadPdf: 'Unduh Laporan PDF Resmi',
    calc_consultationText: 'Ingin survei lokasi fisik secara gratis dan penawaran harga resmi yang disesuaikan dari Tim Engineering ACE?',
    calc_consultationLink: 'Klik Selengkapnya Untuk Konsultasi Lebih Lanjut',
    calc_btnBack: 'Kembali',
    calc_btnNext: 'Lanjutkan',
    calc_pdfTitle: 'LAPORAN ANALISIS KELAYAKAN PLTS',
    calc_pdfDocNo: 'No Dokumen',
    calc_pdfDate: 'Tanggal',
    calc_pdfSub: 'Laporan Teknis Rekomendasi Investasi Energi Surya',
    calc_pdfSec1: '1. Informasi Umum Klien',
    calc_pdfClientName: 'Nama Klien / Perusahaan',
    calc_pdfClientPhone: 'Nomor Telepon / WhatsApp',
    calc_pdfClientEmail: 'Alamat Email',
    calc_pdfSec2: '2. Parameter Masukan Teknis',
    calc_pdfParam: 'Parameter Masukan',
    calc_pdfVal: 'Nilai Input',
    calc_pdfDesc: 'Keterangan',
    calc_pdfRoofAreaDesc: 'Luas fisik yang dialokasikan untuk instalasi panel PV.',
    calc_pdfGridDesc: 'Kapasitas jaringan daya listrik aktif di lokasi.',
    calc_pdfBillDesc: 'Dasar perhitungan kebutuhan energi harian.',
    calc_pdfSec3: '3. Hasil Analisis Kapasitas & Evaluasi ROI',
    calc_pdfMetric: 'Metrik Evaluasi Sistem',
    calc_pdfEstVal: 'Nilai Estimasi',
    calc_pdfTechDesc: 'Keterangan Teknis',
    calc_pdfRecKwpDesc: 'Kapasitas optimal yang disesuaikan luas atap & daya PLN.',
    calc_pdfAnnGen: 'Estimasi Produksi Energi Listrik',
    calc_pdfAnnGenDesc: 'Mengacu pada sun hours harian rata-rata di Indonesia.',
    calc_pdfAnnGenUnit: 'kWh / Tahun',
    calc_pdfAnnSavings: 'Estimasi Penghematan Finansial',
    calc_pdfAnnSavingsDesc: 'Atau setara dengan {savings} / Bulan.',
    calc_pdfPaybackDesc: 'Asumsi biaya sistem rata-rata standar ACE.',
    calc_pdfCo2Desc: 'Sertifikasi hijau kontribusi pelaporan keberlanjutan.',
    calc_pdfSec4: '4. Urutan Rekomendasi Produk Panel Surya Terbaik',
    calc_pdfSec4Note: 'Diurutkan secara otomatis berdasarkan prioritas performa, durasi garansi pabrikan, dan nilai ekonomis investasi.',
    calc_pdfRank: 'Peringkat',
    calc_pdfPanelBrand: 'Merek & Model Panel',
    calc_pdfTechSpec: 'Spesifikasi Teknis',
    calc_pdfEstPrice: 'Estimasi Harga',
    calc_pdfCloseness: 'Tingkat Kecocokan',
    calc_pdfFormNote: 'Catatan: Untuk melakukan konsultasi lanjutan dan penjadwalan survei fisik terperinci, silakan hubungi tim teknik melalui tautan kuesioner Google Form berikut: {url}',
    calc_pdfCreatedBy: 'Dibuat Oleh,',
    calc_pdfApprovedBy: 'Disetujui Oleh,',
    calc_pdfClientRep: 'Perwakilan Klien / Kemitraan',
    calc_pdfSigLine: 'Tanda Tangan & Nama Terang',
    calc_pdfSeniorTech: 'Technician Engineer Senior'
  },
  ko: {
    nav_home: "홈", nav_about: "회사소개", nav_strength: "강점", nav_services: "서비스", nav_projects: "프로젝트", nav_contact: "연락처", nav_calculator: "계산기",
    hero_badge: "인도네시아 No.1 태양광 EPC 및 O&M", hero_title: "미래를 깨끗한 에너지로 <span class='gold-text'>활성화</span>", hero_desc: "프리미엄 태양광 솔루션 — EPC, O&M 및 산업, 상업, 주거, 농업을 위한 재생 혁신.", hero_btn1: "더 알아보기", hero_btn2: "문의하기",
    about_tag: "회사소개", about_title: "태양광 분야의 신뢰받는 파트너", about_desc: "PT. ACE ENERGY SERVICE(30년 이상 경력의 B2 등급 건설 리더 ACE E&C 계열사)는 인도네시아 전역에 세계적 수준의 태양광 PV 솔루션을 제공합니다. 2019년부터 EPC, O&M 및 혁신적인 재생 서비스를 전문으로 합니다.", about_stat1: "300+ 그룹 프로젝트", about_stat2: "ISO 및 B2 인증", about_stat3: "전국 포트폴리오", about_stat4: "IDR 1.2T 매출(2023년)",
    counter1: "우수성의 해", counter2: "주요 프로젝트", counter3: "설치 용량", counter4: "법인 고객",
    strengths_tag: "선택 이유", strengths_title: "핵심 강점", strengths_sub: "모든 프로젝트의 품질, 신뢰성 및 혁신.",
    strength1_title: "전문가 팀", strength1_desc: "엔지니어링, 법무, 비즈니스 분야의 다학제 전문가.",
    strength2_title: "국제 표준", strength2_desc: "글로벌 IEC/ISO 벤치마크를 충족하는 설계 및 자재.",
    strength3_title: "지속 가능한 우수성", strength3_desc: "최적화된 에너지, 장기적 탈탄소 영향.",
    strength4_title: "Tier-1 자재", strength4_desc: "고품질 부품 및 최신 태양광 기술.",
    services_tag: "종합 솔루션", services_title: "핵심 서비스", services_sub: "EPC에서 O&M까지 종합 태양광 서비스",
    service1_title: "태양광 O&M 서비스", service1_desc: "24/7 모니터링, 예측 유지보수, 신속 수리 및 성능 보고.",
    service2_title: "상업용 EPC", service2_desc: "공장, 쇼핑몰, 사무실을 위한 턴키 설치 및 유연한 자금 조달.",
    service3_title: "주거용 EPC", service3_desc: "옥상 태양광, 25년 패널 보증, 모니터링 앱 및 사후 지원.",
    service4_title: "농업용 태양광", service4_desc: "관개 펌프, 태양광 냉방, 오프그리드/하이브리드 — 비용 절감.",
    service5_title: "REC 관리", service5_desc: "I-REC 인증, 탄소 중립 보고 및 ESG 지원.",
    service6_title: "BESS 솔루션", service6_desc: "에너지 저장: 피크 이동, 계통 안정성, 비상 전원.",
    service7_title: "PPP 및 IPP 프로젝트", service7_desc: "BOT, BOO 모델 — PPA 구조화 및 대규모 태양광 발전소 전문.",
    projects_tag: "포트폴리오", projects_title: "주요 프로젝트", projects_sub: "인도네시아 태양광 분야에서 입증된 우수성",
    filter_all: "전체 프로젝트", filter_industrial: "산업", filter_commercial: "상업", filter_rooftop: "옥상",
    view_details: "자세히 보기",
    legacy_tag: "우리의 유산", legacy_title: "ACE Energy Service를 선택해야 하는 이유?",
    legacy1: "<strong>B2 등급 라이선스</strong> – 인도네시아 최고 등급",
    legacy2: "<strong>엄격한 HSE 및 품질 기준</strong> – ISO 9001, 14001, 45001",
    legacy3: "<strong>비용 효율적인 스킴</strong> – 선투자 없이 전기료 절감",
    legacy4: "<strong>DUNS 등록 및 국제 REC 파트너</strong>",
    milestone_title: "이정표",
    milestone1: "<strong>2019</strong> – ACE ENERGY SERVICE 출범",
    milestone2: "<strong>2021-2023</strong> – 11 MWp 한국타이어, 4 MWp 화승",
    milestone3: "<strong>2025</strong> – 국가 목표 42.6 GW 지원",
    // Contact
    contact_tag: "연락하기", contact_title: "더 푸른 미래를 함께 만들어요", contact_form_title: "메시지 보내기",
    contact_name: "이름", contact_email: "이메일", contact_message: "메시지", contact_send: "문의 보내기",
    // Footer
    footer_text: "2019년부터 인도네시아 No.1 태양광 EPC 및 O&M", footer_links: "빠른 링크", footer_cert: "인증", footer_follow: "팔로우", copyright: "© 2026 ACE ENERGY SERVICE. 모든 권리 보유.",
    modal_capacity: "용량:", modal_button: "문의하기",
    calc_step1Label: '기본 정보',
    calc_step2Label: '태양광 요구사양',
    calc_step3Label: '추천 결과',
    calc_step1Title: '1단계: 기본 정보',
    calc_step1Desc: '공식 태양광 제안서 작성을 위해 이름, 전화번호 및 이메일을 입력해 주세요.',
    calc_clientNameLabel: '성명 / 회사명',
    calc_clientNamePlaceholder: '성명을 입력해 주세요...',
    calc_clientPhoneLabel: '전화번호 / WhatsApp',
    calc_clientPhonePlaceholder: '예: 087770051282',
    calc_clientEmailLabel: '이메일 주소',
    calc_clientEmailPlaceholder: '예: name@domain.com',
    calc_alertFillProfile: '먼저 이름, 전화번호, 이메일 정보를 입력해 주세요.',
    calc_step2Title: '2단계: 기술 데이터 및 전력 소비량',
    calc_step2Desc: '권장 태양광 용량을 계산하기 위해 가용 지붕 면적과 한전(PLN) 계약 전력 정보를 입력해 주세요.',
    calc_roofAreaLabel: '가용 지붕 면적 (m²)',
    calc_roofAreaNote: '표준 면적: 태양광 패널 1 kWp 설치 시 약 5-6 m²의 빈 지붕 공간이 필요합니다.',
    calc_gridCapacityLabel: 'PLN 계약 전력 용량 (VA)',
    calc_monthlyBillLabel: '월평균 전기 요금 (IDR)',
    calc_idealKwp: '이상적 용량',
    calc_maxKwp: '지붕 한계',
    calc_recKwp: '권장 용량',
    calc_step3Title: '3단계: ROI 분석 및 제품 순위',
    calc_step3Desc: 'ROI 분석이 완료되었습니다. 입력하신 정보를 바탕으로 한 태양광 타당성 재무 보고서 및 최적의 제품 추천 결과입니다.',
    calc_estSavings: '월간 예상 절감액',
    calc_paybackPeriod: '투자 회수 기간',
    calc_years: '년',
    calc_co2Offset: '연간 CO2 감축량',
    calc_tons: '톤',
    calc_selectedPanels: '고객님을 위한 추천 태양광 패널',
    calc_price: '가격',
    calc_efficiency: '효율',
    calc_warranty: '보증',
    calc_noProducts: '지붕 호환성 필터 규칙을 통과한 제품이 없습니다.',
    calc_downloadPdf: '공식 PDF 보고서 다운로드',
    calc_consultationText: 'ACE 엔지니어링 팀의 무료 현장 실사 및 맞춤형 공식 견적을 원하십니까?',
    calc_consultationLink: '추가 상담을 위해 여기를 클릭하세요',
    calc_btnBack: '이전',
    calc_btnNext: '다음',
    calc_pdfTitle: '태양광 발전 타당성 분석 보고서',
    calc_pdfDocNo: '문서 번호',
    calc_pdfDate: '일자',
    calc_pdfSub: '태양광 에너지 투자 추천 기술 보고서',
    calc_pdfSec1: '1. 고객 일반 정보',
    calc_pdfClientName: '고객명 / 회사명',
    calc_pdfClientPhone: '전화번호 / WhatsApp',
    calc_pdfClientEmail: '이메일 주소',
    calc_pdfSec2: '2. 기술 입력 매개변수',
    calc_pdfParam: '입력 항목',
    calc_pdfVal: '입력값',
    calc_pdfDesc: '설명',
    calc_pdfRoofAreaDesc: '태양광 패널 설치를 위해 할당된 물리적 면적입니다.',
    calc_pdfGridDesc: '해당 사이트의 활성 전력 그리드 용량입니다.',
    calc_pdfBillDesc: '일일 에너지 요구량 계산의 기준입니다.',
    calc_pdfSec3: '3. 용량 분석 및 ROI 평가 결과',
    calc_pdfMetric: '시스템 평가 지표',
    calc_pdfEstVal: '추정값',
    calc_pdfTechDesc: '기술적 설명',
    calc_pdfRecKwpDesc: '지붕 면적 및 PLN 계약 전력에 맞게 조정된 최적의 용량입니다.',
    calc_pdfAnnGen: '예상 발전량',
    calc_pdfAnnGenDesc: '인도네시아의 일평균 일조 시간을 기준으로 합니다.',
    calc_pdfAnnGenUnit: 'kWh / 년',
    calc_pdfAnnSavings: '예상 재무 절감액',
    calc_pdfAnnSavingsDesc: '또는 월 {savings} 상당.',
    calc_pdfPaybackDesc: 'ACE 표준 평균 시스템 비용을 가정한 것입니다.',
    calc_pdfCo2Desc: '지속가능성 보고에 기여하는 친환경 인증입니다.',
    calc_pdfSec4: '4. 최적의 태양광 패널 제품 추천 순위',
    calc_pdfSec4Note: '성능 우수성, 제조업체 보증 기간 및 투자 경제성을 기준으로 자동 정렬되었습니다.',
    calc_pdfRank: '순위',
    calc_pdfPanelBrand: '패널 브랜드 및 모델',
    calc_pdfTechSpec: '기술 사양',
    calc_pdfEstPrice: '예상 가격',
    calc_pdfCloseness: '적합도',
    calc_pdfFormNote: '참고: 추가 상담 및 상세 현장 실사 일정을 잡으려면 다음 Google 설문지 링크를 통해 엔지니어링 팀에 문의하십시오: {url}',
    calc_pdfCreatedBy: '작성자:',
    calc_pdfApprovedBy: '승인자:',
    calc_pdfClientRep: '고객 대표 / 파트너',
    calc_pdfSigLine: '서명 및 성명',
    calc_pdfSeniorTech: '수석 기술 엔지니어'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('lang') || 'en';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('lang', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
